// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9BUezFBVqy3N5U0PSPE7ms9U9BtzZeAE',
    appId: '1:1032373936101:web:4e2e5a3f4bbee46a59190c',
    messagingSenderId: '1032373936101',
    projectId: 'smart-home-assistant-d3c46',
    authDomain: 'smart-home-assistant-d3c46.firebaseapp.com',
    storageBucket: 'smart-home-assistant-d3c46.firebasestorage.app',
    measurementId: 'G-RTZKKL0BWN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU97MOqVrRqqpkfDqleN5iCcK4fgkeHz0',
    appId: '1:1032373936101:android:89b531fa9bd47c5a59190c',
    messagingSenderId: '1032373936101',
    projectId: 'smart-home-assistant-d3c46',
    storageBucket: 'smart-home-assistant-d3c46.firebasestorage.app',
  );
}
